/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

declare module 'vue' {
    export interface GlobalComponents {
        ABackTop: typeof import('ant-design-vue/es')['BackTop']
        AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
        ADivider: typeof import('ant-design-vue/es')['Divider']
        CharacterCard: typeof import('./components/translate-table/CharacterCard.vue')['default']
        CharacterList: typeof import('./components/translate-table/CharacterList.vue')['default']
        DarkmodeSwitch: typeof import('./components/DarkmodeSwitch.vue')['default']
        Footer: typeof import('./components/translate-table/Footer.vue')['default']
        Header: typeof import('./components/translate-table/Header.vue')['default']
        NavBar: typeof import('./components/NavBar.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        TranslateTable: typeof import('./components/translate-table/TranslateTable.vue')['default']
    }
}
